commands:
  #greeting
  - command:
    input: oi
    entity: greeting
    action: greet
 #hora
  - command:
    input: horas 
    entity: time  
    action: getTime
    -command:
    input: horas
    entity: time  
    action: getTime
  #data
  - command:
    input: dia
    entity: date  
    action: getDate
  - command:
    input: data
    entity: date  
    action: getDate
  - command:
    input: hoje
    entity: date  
    action: getDate
  #Open
  - command:
    input: bloco de notas
    entity: open  
    action: getnotePad
  - command:
    input: bloco de notas
    entity: open  
    action: getnotePad
  - command:
    input: navegador
    entity: open  
    action: getGoogle
  - command:
    input: navegador
    entity: open  
    action: getGoogle
 