commands:
  - command: 
    input: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    entity: none
    action: none
  #greeting
  - command:
    input: oi
    entity: greeting
    action: greet
 #hora
  - command:
    input: que horas sao 
    entity: time  
    action: getTime
    -command:
    input: me diga as horas
    entity: time  
    action: getTime
  #data
  - command:
    input: que dia e hoje
    entity: date  
    action: getDate
  - command:
    input: me diga a data
    entity: date  
    action: getDate
  #Open
  - command:
    input: abrir bloco de notas
    entity: open  
    action: getnotePad
  - command:
    input: abrir bloco de notas
    entity: open  
    action: getnotePad
  - command:
    input: abrir navegador
    entity: open  
    action: getGoogle
  - command:
    input: abrir navegador
    entity: open  
    action: getGoogle
 